version: '3'

services:
  web:
    build: .
    tty: true
    command: python3 mysite/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - backend

networks:
  backend:
    driver: bridge